name: 'ATS Portal Api'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run_number:
        type: int
        required: true
        description: 'Run number of Build & Dev CICD'

env:
  REPO: APL.ATS.Portal.Api
  PROD_CICD: ats_portal_api_deploy_PROD_cicd.yml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy_PROD:
    name: "Deploy / PROD"
    environment: PROD
    runs-on: ubuntu-latest
    steps:
    - name: PROD deployment by Github Script
      uses: actions/github-script@v6.2.0
      with:
        github-token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
        debug: true
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: '${{ env.REPO }}'
            workflow_id: '${{ env.PROD_CICD }}',
            ref: 'main',
            inputs: { 'run_number': '${{ github.event.inputs.run_number }}' }
          })
      
    - name: PROD deployment
      id: triggered_PROD
      uses: convictional/trigger-workflow-and-wait@v1.6.3
      with:
        owner: context.repo.owner
        repo: ${{ env.REPO }}
        github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
        workflow_file_name: ${{ env.PROD_CICD }}
        github_user: ${{ github.actor }}
        client_payload: |
          {
            "run_number": "${{ github.event.inputs.run_number }}"
          }
    - name: Get result
      run: echo "${{ steps.triggered_PROD.outputs.result }}"
