name: 'ATS Portal Api'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run_number:
        type: int
        required: true
        description: 'Run number of Build & Dev CICD'

env:
  REPO: APL.ATS.Portal.Api

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
#  Deploy_DEV:
#    name: "Deploy / DEV"
#    environment: DEVELOPMENT
#    runs-on: ubuntu-latest
#    outputs:
#      run_number: ${{ fromJson(steps.query_run.outputs.response).run_number }}
#    steps:
#    - uses: haya14busa/action-cond@v1
#      id: condval
#      with:
#        cond: ${{ github.event.inputs.branch == '' }}
#        if_true: 'master'
#        if_false: '${{ github.event.inputs.branch }}'
#    - name: "Build & Deploy / DEV"
#      id: build_deploy_DEV
#      uses: mathze/workflow-dispatch-action@v1.1.0
#      with:
#        owner: ${{ env.OWNER }}
#        repo: ${{ env.REPO }}
#        token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
#        workflow-name: ats_portalapi_deploy_DEV_cicd.yml
#        ref: ${{ steps.condval.outputs.value }}
#        fail-on-error: true
#        run-id: dummy
#    - name: Query run from build_deploy_DEV
#      id: query_run
#      uses: fjogeleit/http-request-action@v1
#      with:
#        url: ${{ format('https://api.github.com/repos/{0}/{1}/actions/runs/{2}', env.OWNER, env.REPO, steps.build_deploy_DEV.outputs.run-id) }}
#        method: 'GET'
#        customHeaders: |
#          {
#            "accept": "application/vnd.github+json",
#            "Authorization": "${{ format('token {0}', secrets.G_PERSONAL_ACCESS_TOKEN) }}"
#          }

  Deploy_PROD:
    name: "Deploy / PROD"
    environment: PROD
    runs-on: ubuntu-latest
    steps:
#    - uses: mathze/workflow-dispatch-action@v1.1.0
#      with:
#        owner: ${{ env.OWNER }}
#        repo: ${{ env.REPO }}
#        token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
#        workflow-name: ats_portal_api_deploy_PROD_cicd.yml
#        ref: 'feature/DEVOPS-17-implement-cicd-for-ats-portal-api-to-production'
#        fail-on-error: true
#        run-id: dummy
#        payload: |
#          {
#            "run_number": "${{ github.event.inputs.run_number }}"
#          }
    - uses:  actions/github-script@v6
      id: create_PROD_deployment
      with:
        github-token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: '${{ env.REPO }}',
            workflow_id: 'ats_portalapi_deploy_DEV_cicd.yml',
            ref: 'master',
          })
    - name: Get result
      run: echo "${{steps.create_PROD_deployment.outputs.result}}"
