# This is a basic workflow to help you get started with Actions

name: 'ATS Portal Api'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy_DEV:
    name: "Deploy / DEV"
    environment: DEVELOPMENT
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ steps.build_deploy_DEV.outputs.run-id }}
      run_number: ${{ steps.build_deploy_DEV.outputs.run_number }}
    steps:
    - name: "Build & Deploy / DEV"
      id: build_deploy_DEV
      uses: mathze/workflow-dispatch-action@v1.1.0
      with:
        owner: ApolloEnglishVN
        repo: APL.ATS.Portal.Api
        token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
        workflow-name: ats_portalapi_deploy_DEV_cicd.yml
        ref: 'feature/workflow_triggered_from_other_repo'
        fail-on-error: true
    - name: Dump outputs of Deploy_DEV
      run: echo '${{ toJSON(steps.build_deploy_DEV.outputs) }}'
        
  Deploy_QC:
    name: "Deploy / QC"
    environment: QC
    runs-on: ubuntu-latest
    needs: Deploy_DEV
    steps:
    - uses: mathze/workflow-dispatch-action@v1.1.0
      with:
        owner: ApolloEnglishVN
        repo: APL.ATS.Portal.Api
        token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
        workflow-name: ats_portal_api_deploy_QC_cicd.yml
        ref: 'feature/workflow_triggered_from_other_repo'
        fail-on-error: true
        payload: |
          {
            "run_number": "${{ needs.Deploy_DEV.outputs }}"
          }
        
